#pragma once

const char* img_urls[] = {
    ".bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/001.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/002.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/003.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/004.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/005.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/006.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/007.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/008.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/009.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/010.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/011.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/012.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/013.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/014.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/015.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/016.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/017.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/018.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/019.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/020.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/021.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/022.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/023.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/024.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/025.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/026.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/027.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/028.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/029.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/030.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/031.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/032.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/033.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/034.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/035.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/036.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/037.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/038.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/039.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/040.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/041.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/042.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/043.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/044.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/045.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/046.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/047.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/048.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/049.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/050.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/051.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/052.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/053.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/054.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/055.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/056.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/057.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/058.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/059.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/060.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/061.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/062.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/063.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/064.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/065.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/066.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/067.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/068.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/069.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/070.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/071.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/072.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/073.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/074.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/075.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/076.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/077.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/078.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/079.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/080.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/081.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/082.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/083.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/084.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/085.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/086.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/087.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/088.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/089.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/090.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/091.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/092.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/093.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/094.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/095.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/096.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/097.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/098.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/099.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/100.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/101.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/102.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/103.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/104.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/105.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/106.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/107.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/108.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/109.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/110.bmp",

    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/111.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/112.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/113.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/114.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/115.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/116.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/117.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/118.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/119.bmp",
    "C:/source/BitmapLoader/BitmapLoader/resources/castle-1/120.bmp"
};